language: node_js
node_js:
- '6'
sudo: false
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  directories:
  - node_modules
install:
- npm install
script:
- sidekick run --ci
- npm run test-ci
after_script:
- cat ./test-coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    rooms:
      secure: h7i5lpu11sacvB8yiE7asdG2Uh6q8EqfaJMCfKG/R//YvfYkNlNt9S+jLNQseDn4dutTF/dQKhDiMJz6Izbg1sfDcCOMN2zSDfwcHRPySYg5/Ro10kTdGZz/DFJHteZnM5D5PcWfknzDhOExPpx8CZ2HSroesIsj4LZQ+xAgyoSZkZB2UIUKtCikW2uA+0YgOsboWwbQrLQYiIAidJa60DxuBJCVIBnLzbcqjBwWoDPOBKRKh0zFiHFcbiI4mpTyj1eGoHesUHhmOXHvzE2ifWiZzXIWFiGSGP1tnxM8A46teCYIyrVhyGeCwZqptp7oPjB5Wqct5h6/Z4zs17d4du0PAYTpsIL9jk9guyXJkur+nGXISlT8sRQa10+J6j6pxqHqDtAxrBXQqP/M6smSgBAt+GkoFLIYlMDUwqGR8Dppzdg8kcPhXD+vd6++BcNyBPYyWErbVRImvQ1fCr357UBKDUr8WNs/AaHKnlYzKkS1/mKq/mXpxtxDuHij2MUByFF7+/wNWM63Ijd1qWD5v6q5PLWYPWfFa2IQLytt2OXySiJNoiSjVikKZLbDVNVds++HfKISprcIZtEnct/gJ+LK8c3lEASv3Tp2zcX2lCqADSd5NgnIqKSfDuocCmTQrcqaLeSSEWxXxfFAKTrUNGKgUVUxUUXDwBln0JOzAWE=
